services:
  - type: web
    name: dnc-portal-backend
    env: python
    plan: starter
    buildCommand: |
      cd backend
      pip install poetry
      poetry install
      poetry run alembic upgrade head
    startCommand: |
      cd backend
      poetry run uvicorn do_not_call.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg2://traadmin:TPSZen2025%40%21@dnc.postgres.database.azure.com:5432/postgres?sslmode=require
      - key: PGHOST
        value: dnc.postgres.database.azure.com
      - key: PGUSER
        value: traadmin
      - key: PGPORT
        value: 5432
      - key: PGDATABASE
        value: postgres
      - key: PGPASSWORD
        value: TPSZen2025@!
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: RINGCENTRAL_CLIENT_ID
        value: a2fq2a96nVteLDto4T6aO1
      - key: RINGCENTRAL_CLIENT_SECRET
        value: VNlTiJWla6qapMjlzlquvgWD5JT2DKSIQaqUrHIVKk6y
      - key: RINGCENTRAL_JWT
        value: eyJraWQiOiI4NzYyZjU5OGQwNTk0NGRiODZiZjVjYTk3ODA0NzYwOCIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJhdWQiOiJodHRwczovL3BsYXRmb3JtLnJpbmdjZW50cmFsLmNvbS9yZXN0YXBpL29hdXRoL3Rva2VuIiwic3ViIjoiNjM2NjM4OTcwMDciLCJpc3MiOiJodHRwczovL3BsYXRmb3JtLnJpbmdjZW50cmFsLmNvbSIsImV4cCI6MzkwNTE4NzM0OSwiaWF0IjoxNzU3NzAzNzAyLCJqdGkiOiJJeWhTTlZiT1FHQ0ZLZnNWYlVXOTB3In0.T3OLsRHBpm9e0Kc-SsERMWevhRH-KS2wXLbkuMC2dxD2xCBhEEF81tVKqvXInwgJPpuUjymmw2ot4IgU9BIItrNN0-loo66Q8_WAITZezmdNwSJN09VCrDfXVT1lQDo0jUANBPmKLE8IPv9kg51V_Q2htTAVHIC-5Wfe4lyZ5HPYy6R_-iMB7GV72tCdeCKkz9D0wsKppaf0U48UVRGTx1FjaYXjMnLZ5orwPiHoFbrqF6F1kjrr6raotYmJRDE09YQVginFj5FtFNXwWlCff9NooVgK4z9U5jRMzY6yK4pY-XXXcSh4DeVC5W7O7SS6uvzothF535EtfXojRpfeuw

  - type: static_site
    name: dnc-portal-frontend
    plan: starter
    buildCommand: |
      cd frontend
      npm install -g pnpm
      pnpm install
      pnpm build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://dnc-portal-backend.onrender.com
      - key: VITE_ENTRA_TENANT_ID
        value: 185fc38c-2c1b-4307-a164-24a4072e83e1
      - key: VITE_ENTRA_SPA_CLIENT_ID
        value: a2a6c2c2-cb10-411e-a354-da61bfa4a3b2
      - key: VITE_ENTRA_SCOPE
        value: api://a2a6c2c2-cb10-411e-a354-da61bfa4a3b2/access_as_user