# Render Blueprint for DNC Portal
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: dnc-backend
    env: docker
    plan: starter
    rootDir: backend
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "8000"
      - key: HOST
        value: 0.0.0.0
      - key: RELOAD
        value: "false"
      - key: DATABASE_URL
        fromSecret: AZURE_POSTGRES_URL
      - key: UPLOADS_DIR
        value: /data/uploads
      - key: LOG_LEVEL
        value: INFO
      - key: ENTRA_TENANT_ID
        fromSecret: ENTRA_TENANT_ID
      - key: ENTRA_AUDIENCE
        fromSecret: ENTRA_AUDIENCE
      - key: ENTRA_REQUIRE_SIGNATURE
        value: "true"
      - key: ALLOWED_ORIGIN_REGEX
        value: ".*"
    disk:
      name: dnc-data
      mountPath: /data
      sizeGB: 1

  - type: web
    name: dnc-frontend
    env: node
    rootDir: frontend
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm build
    startCommand: npx serve -s dist -l $PORT
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: dnc-backend
          property: url
      - key: VITE_ENTRA_SPA_CLIENT_ID
        fromSecret: ENTRA_SPA_CLIENT_ID
      - key: VITE_ENTRA_TENANT_ID
        fromSecret: ENTRA_TENANT_ID
      - key: VITE_ENTRA_SCOPE
        fromSecret: ENTRA_SCOPE
