services:
  - type: web
    name: dnc-portal-backend
    env: python
    plan: starter
    buildCommand: |
      cd backend
      pip install poetry
      poetry install
      poetry run alembic upgrade head
    startCommand: |
      cd backend
      poetry run uvicorn do_not_call.main:app --host 0.0.0.0 --port $PORT
    envVars:
      # Database Configuration
      - key: PGHOST
        value: "dnc.postgres.database.azure.com"
      - key: PGUSER
        value: "traadmin"
      - key: PGPORT
        value: "5432"
      - key: PGDATABASE
        value: "postgres"
      - key: PGPASSWORD
        value: "TPSZen2025@!"

      # Azure Database Configuration
      - key: AZURE_DB_CLIENT_ID
        value: "a2a6c2c2-cb10-411e-a354-da61bfa4a3b2"
      - key: AZURE_DB_CLIENT_SECRET
        value: ""
      - key: AZURE_DB_TENANT_ID
        value: "185fc38c-2c1b-4307-a164-24a4072e83e1"
      - key: PGSSLMODE
        value: "require"
      - key: PGREQUIRESSL
        value: "1"
      - key: PGGSSENCMODE
        value: "disable"
      - key: PGGSSAUTH
        value: "disable"

      # Application Settings
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "debug"
      - key: RELOAD
        value: "false"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8000"
      - key: ENVIRONMENT
        value: "production"

      # Feature Flags
      - key: ENABLE_PROVIDERS
        value: "true"

      # Azure/Entra Configuration
      - key: ENTRA_AUDIENCE
        value: "api://a2a6c2c2-cb10-411e-a354-da61bfa4a3b2"
      - key: ENTRA_REQUIRE_SIGNATURE
        value: "true"
      - key: ENTRA_TENANT_ID
        value: "185fc38c-2c1b-4307-a164-24a4072e83e1"
      - key: AZURE_DB_CLIENT_ID
        value: "a2a6c2c2-cb10-411e-a354-da61bfa4a3b2"
      - key: AZURE_DB_CLIENT_SECRET
        value: ""
      - key: AZURE_DB_TENANT_ID
        value: "185fc38c-2c1b-4307-a164-24a4072e83e1"

      # File Uploads
      - key: UPLOADS_DIR
        value: "/data/uploads"
      - key: ALLOWED_ORIGIN_REGEX
        value: ".*"

      # Test Configuration
      - key: TEST_PHONE_NUMBER
        value: "5618189087"
      - key: TEST_PHONE_CODE
        value: "1"

      # Ytel Configuration
      - key: YTEL_USER
        value: "103"
      - key: YTEL_PASSWORD
        value: "bHSQPgE7J6nLzX"
      - key: YTEL_CAMPAIGN_ID
        value: "1000"
      - key: YTEL_LIST_ID
        value: "999"
      - key: YTEL_FIRST_NAME
        value: "Reactivated"
      - key: YTEL_LAST_NAME
        value: "Lead"

      # Convoso Configuration
      - key: CONVOSO_AUTH_TOKEN
        value: "swai20svbj229p1f3cozei7uxbsbvyne"
      - key: CONVOSO_LEADS_AUTH_TOKEN
        value: "phoq164rreu46tstut4eoth7zrenccsr"
      - key: CONVOSO_CAMPAIGN_ID
        value: "0"

      # RingCentral Configuration
      - key: RINGCENTRAL_CLIENT_ID
        value: "a2fq2a96nVteLDto4T6aO1"
      - key: RINGCENTRAL_CLIENT_SECRET
        value: "VNlTiJWla6qapMjlzlquvgWD5JT2DKSIQaqUrHIVKk6y"
      - key: RINGCENTRAL_JWT
        value: "eyJraWQiOiI4NzYyZjU5OGQwNTk0NGRiODZiZjVjYTk3ODA0NzYwOCIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJhdWQiOiJodHRwczovL3BsYXRmb3JtLnJpbmdjZW50cmFsLmNvbS9yZXN0YXBpL29hdXRoL3Rva2VuIiwic3ViIjoiNjM2NjM4OTcwMDciLCJpc3MiOiJodHRwczovL3BsYXRmb3JtLnJpbmdjZW50cmFsLmNvbSIsImV4cCI6MzkwNTE4NzM0OSwiaWF0IjoxNzU3NzAzNzAyLCJqdGkiOiJJeWhTTlZiT1FHQ0ZLZnNWYlVXOTB3In0.T3OLsRHBpm9e0Kc-SsERMWevhRH-KS2wXLbkuMC2dxD2xCBhEEF81tVKqvXInwgJPpuUjymmw2ot4IgU9BIItrNN0-loo66Q8_WAITZezmdNwSJN09VCrDfXVT1lQDo0jUANBPmKLE8IPv9kg51V_Q2htTAVHIC-5Wfe4lyZ5HPYy6R_-iMB7GV72tCdeCKkz9D0wsKppaf0U48UVRGTx1FjaYXjMnLZ5orwPiHoFbrqF6F1kjrr6raotYmJRDE09YQVginFj5FtFNXwWlCff9NooVgK4z9U5jRMzY6yK4pY-XXXcSh4DeVC5W7O7SS6uvzothF535EtfXojRpfeuw"
      - key: RINGCENTRAL_JWT_ASSERTION
        value: "eyJraWQiOiI4NzYyZjU5OGQwNTk0NGRiODZiZjVjYTk3ODA0NzYwOCIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJhdWQiOiJodHRwczovL3BsYXRmb3JtLnJpbmdjZW50cmFsLmNvbS9yZXN0YXBpL29hdXRoL3Rva2VuIiwic3ViIjoiNjM2NjM4OTcwMDciLCJpc3MiOiJodHRwczovL3BsYXRmb3JtLnJpbmdjZW50cmFsLmNvbSIsImV4cCI6MzkwNTE4NzM0OSwiaWF0IjoxNzU3NzAzNzAyLCJqdGkiOiJJeWhTTlZiT1FHQ0ZLZnNWYlVXOTB3In0.T3OLsRHBpm9e0Kc-SsERMWevhRH-KS2wXLbkuMC2dxD2xCBhEEF81tVKqvXInwgJPpuUjymmw2ot4IgU9BIItrNN0-loo66Q8_WAITZezmdNwSJN09VCrDfXVT1lQDo0jUANBPmKLE8IPv9kg51V_Q2htTAVHIC-5Wfe4lyZ5HPYy6R_-iMB7GV72tCdeCKkz9D0wsKppaf0U48UVRGTx1FjaYXjMnLZ5orwPiHoFbrqF6F1kjrr6raotYmJRDE09YQVginFj5FtFNXwWlCff9NooVgK4z9U5jRMzY6yK4pY-XXXcSh4DeVC5W7O7SS6uvzothF535EtfXojRpfeuw"
      - key: RINGCENTRAL_BASIC_B64
        value: "YTJmcTJhOTZuVnRlTER0bzRUNmFPMTpWTmxUaUpXbGE2cWFwTWpsemxxdXZnV0Q1SlQyREtTSVFhcVVySElWS2s2eQ=="
      - key: RINGCENTRAL_DNC_STATUS
        value: "Blocked"

      # Genesys Configuration
      - key: GENESYS_CLIENT_ID
        value: "efc1134d-8252-4aea-a995-47b1dc0c5fba"
      - key: GENESYS_CLIENT_SECRET
        value: "o2Tqu6dXnLKvI3UAg5iRkzb6MwGvXrlUrzO1kaGguCY"
      - key: GENESYS_DNCLIST_ID
        value: "d4a6a02e-4ab9-495b-a141-4c65aee551db"

      # Logics Configuration
      - key: LOGICS_BASIC_AUTH_B64
        value: "NDkxN2ZhMGNlNDY5NDUyOWE5Yjk3ZWFkMWE2MGM5MzI6YTc3YThlNTAtZTllYS00MTg1LThiMGUtYzI0YjQ2OGIyYTM4"
      - key: LOGICS_UPDATE_STATUS_ID
        value: "57"

  - type: web
    name: dnc-portal-frontend
    env: static
    plan: starter
    buildCommand: |
      cd frontend
      npm install -g pnpm
      pnpm install
      pnpm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://dnc-backend-bb96.onrender.com"
      - key: VITE_ENABLE_PROVIDERS
        value: "true"
