name: Deploy Backend (Azure App Service)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch: {}

env:
  AZURE_WEBAPP_NAME: tra-api-backend
  AZURE_RG: TRA-DevOps

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv (faster installer)
        run: pip install uv

      - name: Create requirements.txt from pyproject
        working-directory: backend
        run: |
          uv pip compile pyproject.toml -o requirements.txt

      - name: Remove optional/heavy deps for Azure build
        working-directory: backend
        run: |
          mv requirements.txt requirements.full.txt
          grep -Ev '^(pyodbc|playwright)==|^playwright-core==' requirements.full.txt > requirements.txt
          echo "Final requirements:" && cat requirements.txt

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Python 3.12 runtime on App Service
        run: |
          az webapp config set \
            --resource-group "$AZURE_RG" \
            --name "$AZURE_WEBAPP_NAME" \
            --linux-fx-version "PYTHON|3.12"

      - name: Ensure build during deployment is enabled
        run: |
          az webapp config appsettings set \
            --resource-group "$AZURE_RG" \
            --name "$AZURE_WEBAPP_NAME" \
            --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true

      - name: Configure startup command (Gunicorn/Uvicorn)
        run: |
          # Use PORT provided by App Service at runtime
          az webapp config set \
            --resource-group "$AZURE_RG" \
            --name "$AZURE_WEBAPP_NAME" \
            --startup-file "bash startup.sh"

      - name: Configure CORS/App Settings for SWA origin
        run: |
          az webapp config appsettings set \
            --resource-group "$AZURE_RG" \
            --name "$AZURE_WEBAPP_NAME" \
            --settings \
              ALLOWED_ORIGINS=https://agreeable-glacier-01746f61e.2.azurestaticapps.net \
              RELOAD=false \
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 \
              PYTHONPATH=/home/site/wwwroot \
              WEBSITES_PORT=8000

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: backend

      - name: Restart Web App
        run: az webapp restart --resource-group "$AZURE_RG" --name "$AZURE_WEBAPP_NAME"


