name: Deploy Frontend (Azure Static Web Apps)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_SWA_TOKEN: ${{ secrets.AZURE_SWA_TOKEN }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm i -g pnpm@9

      - name: Install deps
        working-directory: frontend
        run: pnpm install

      - name: Ensure MSAL packages present
        working-directory: frontend
        run: pnpm add @azure/msal-browser @azure/msal-react

      - name: Build
        working-directory: frontend
        env:
          VITE_API_BASE_URL: https://tra-api-backend.azurewebsites.net
          VITE_ENTRA_TENANT_ID: 185fc38c-2c1b-4307-a164-24a4072e83e1
          VITE_ENTRA_SPA_CLIENT_ID: a2a6c2c2-cb10-411e-a354-da61bfa4a3b2
          VITE_ENTRA_SCOPE: api://a2a6c2c2-cb10-411e-a354-da61bfa4a3b2/access_as_user
        run: pnpm run build

      - name: Check SWA token presence
        run: |
          if [ -z "${{ secrets.AZURE_SWA_TOKEN }}" ]; then
            echo "AZURE_SWA_TOKEN is NOT set; will use Azure CLI fallback";
          else
            echo "AZURE_SWA_TOKEN is set; will use SWA deploy action";
          fi

      - name: Verify SWA token
        run: |
          if [ -z "${AZURE_SWA_TOKEN}" ]; then
            echo "AZURE_SWA_TOKEN is not set as a repo secret.";
            exit 1;
          fi

      - name: Install Static Web Apps CLI
        run: npm i -g @azure/static-web-apps-cli@1

      - name: Deploy using SWA CLI
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ env.AZURE_SWA_TOKEN }}
        run: |
          swa deploy ./frontend/dist --env production --deployment-token "$SWA_CLI_DEPLOYMENT_TOKEN"


